### PR TITLE
Samsung Multi Window support

### PR DESCRIPTION
**Pull request by abderrahim**

### CODE REVIEW

**Comment by tuxor1337** [comment]
Is there a reason for the change in the handling of key events?

**Comment by tuxor1337** [comment]
Can you do proper testing for that multiwindow part? I don't have a Samsung device I could test this with.

**Comment by abderrahim** [comment]
The reason for changing the handling of events is explained in the commit message. The pdf is closed as soon as I press the back button, even though i want to long press to get the multiwindow launchers.

And what do you mean by *proper* testing ? I have a galaxy note 8.0, and I've tested that it works fine.

**Comment by tuxor1337** [comment]
Okay, that's fine. With "proper" testing I just wanted to express that it's tested with a setup that actually makes use of that multiwindow feature.

**Pull request merged**
